config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions, only: :index
  get 'questions/search' => 'questions#search'
  get 'questions/top' => 'questions#top'
  get 'questions/signed_in' => 'questions#signed_in'
  get 'questions/answers' => 'questions#answers'
  get 'questions' => 'questions#index'
  resources :tags
  resources :tags do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'questions/similar'
  get 'questions/search_by_id'
  post 'questions/search_id'
  get 'questions/explore'
  post 'tags/follow'
  post 'tags/unfollow'
  get 'profile' => 'profile#show'
end

app/controllers/questions_controller.rb
require "uri"
require "net/http"
require 'json'
require 'will_paginate/array'
class QuestionsController < ApplicationController
  def index
    if not session[:access_token]
      uri = URI('http://localhost:5000/top')
      x = Net::HTTP.get(uri) # => String
      @top = JSON.parse(x)
      # begin
      #   if params.has_key?(:page)
      #     params = {'word': "data-structures", 'page': params[:page]}
      #   else
      #     params = {'word': "data-structures"}
      #   end
      # rescue
      #   pp 'params not found'
      # end
      # params = {'word': "data-structures"}
      # x = Net::HTTP.post_form(URI.parse('http://localhost:5000/result'), params)
      # body = x.body
      # @final_data = JSON.parse(body)
      # @questions = @final_data["all_questions"]
      # @questions = @questions.paginate(page: params[:page], per_page: 10)
      # # @questions = Kaminari.paginate_array(@questions).page(params[:page]).per(10)
      # @pending_questions = @final_data["pending_questions"]
      # @paginatable_array = LinkedTag.order(score: :desc).page(params[:page]).per(20)
      @tags = Tag.all.limit(5).uniq
      @paginatable_array = Kaminari.paginate_array(LinkedTag.order("RANDOM()")).page(params[:page]).per(30)
    else
      uri = URI('http://localhost:5000/top')
      x = Net::HTTP.get(uri) # => String
      @top = JSON.parse(x)
      # begin
      #   if params.has_key?(:page)
      #     params = {'word': "data-structures", 'page': params[:page]}
      #   else
      #     params = {'word': "data-structures"}
      #   end
      # rescue
      #   pp 'params not found'
      # end
      # params = {'word': "data-structures"}
      # x = Net::HTTP.post_form(URI.parse('http://localhost:5000/result'), params)
      # body = x.body
      # @final_data = JSON.parse(body)
      # @questions = @final_data["all_questions"]
      # @questions = @questions.paginate(page: params[:page], per_page: 10)
      # # @questions = Kaminari.paginate_array(@questions).page(params[:page]).per(10)
      # @pending_questions = @final_data["pending_questions"]
      # @paginatable_array = LinkedTag.order(score: :desc).page(params[:page]).per(20)
      @tags = current_user.following_by_type('Tag').order(count: :desc).uniq
      @paginatable_array = Kaminari.paginate_array(LinkedTag.order("RANDOM()")).page(params[:page]).per(30)
    end
  end

  def answers
    get_params = {'access_token': session[:access_token],'site' => 'stackoverflow', 'key' => '6)pzbLQnfOokuC2n)6Xviw(('}
    uri = URI('https://api.stackexchange.com/2.2/me/answers')
    uri.query = URI.encode_www_form(get_params)

    res = Net::HTTP.get_response(uri)

    @final_data = JSON.parse(res.body)
    current_user.update_attributes(answers_response: JSON.parse(res.body), answers_response_updated_at: DateTime.now)
    @final_data["items"].each do |item|
      uri = URI('http://localhost:5000/question?id=' +item["question_id"].to_s)
      x = Net::HTTP.get(uri) # => String
      answers = JSON.parse(x)
      item['highest_score'] = answers["results"][0]["ascore"].to_s
      item['highest_score_id'] = answers["results"][0]["answer_id"].to_s
      item['question'] = answers["results"][0]["question"].to_s
      item['question_id'] = answers["results"][0]["question_id"].to_s
      uri = URI("https://api.stackexchange.com/2.2/questions/#{item['question_id']}/linked?order=desc&sort=activity&site=stackoverflow")
      res = Net::HTTP.get_response(uri)
      item['similar_questions'] = JSON.parse(res.body)
      uri = URI("https://api.stackexchange.com/2.2/questions/#{item['question_id']}/related?order=desc&sort=activity&site=stackoverflow")
      res = Net::HTTP.get_response(uri)
      item['related_questions'] = JSON.parse(res.body)
    end

    uri = URI('https://api.stackexchange.com/2.2/me')
    uri.query = URI.encode_www_form(get_params)
    res = Net::HTTP.get_response(uri)
    @me = JSON.parse(res.body)
    current_user.update_attributes(name: @me['items'][0]['display_name'], reputation: @me['items'][0]['reputation'])
  end

  def signed_in
    code = params['code']

    params = {'client_id' => 12430, 'code' => code, 'client_secret' => '9*Kyrtrtb*iwc6v4soDAuw((', 'redirect_uri' => 'http://localhost:3000/questions/signed_in'}
    x = Net::HTTP.post_form(URI.parse('https://stackoverflow.com/oauth/access_token'), params)
    access_token = x.body.split("=")[1]
    if User.where(auth_token: access_token).present?
    else
      User.create(auth_token: access_token)
    end
    session[:access_token] = access_token
    
    # uri = URI('https://api.stackexchange.com/2.2/me')
    # uri.query = URI.encode_www_form(get_params)
    #
    # res = Net::HTTP.get_response(uri)
    # if res.is_a?(Net::HTTPSuccess)
    #   @final_data = JSON.parse(res.body)
    #   @reputation = @final_data["items"][0]["reputation"]
    # else
    #   @final_data = res.body
    # end

    
    # if has logged in, show questions only relevant to him. Show him
    # how his reputation has increased. And also find some great questions for him to learn from
    # and also learn.

    # also show quetions similar to the ones he has read, sorted by the number of minutes he spent on them.

    # send him questions daily to follow or to answer.

    # help the user build his profile.

    # after this is done, do the same for github.

    # also find if u can use linkedin to see what the user knows also based on the resume he gives.
    redirect_to action: 'index'
  end
  def top
    params = {'word': "data-structures"}
    x = Net::HTTP.post_form(URI.parse('http://localhost:5000/result'), params)
    body = x.body
    @final_data = JSON.parse(body)
    @questions = @final_data["all_questions"]
    @questions = @questions.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.js
    end
  end

  def search_by_id
    
  end

  def search_id
    params = {'id': request.params['question_id']}
    x = Net::HTTP.post_form(URI.parse('http://localhost:5000/search_by_id'), params)
    body = x.body
    @final_data = JSON.parse(body)
    @questions = @final_data["questions"]
    @pending_questions = @final_data["pending_questions"]
  end

  def search
    params = {'word': request.params['q']}
    x = Net::HTTP.post_form(URI.parse('http://localhost:5000/result'), params)
    body = x.body
    @final_data = JSON.parse(body)
    @questions = @final_data["data"]
    @pending_questions = @final_data["pending_questions"]
    tag_id = []
    @final_data['related_tags'].each do |tag|
      pp tag
      tag_id.append(tag.values()[0]['id'])
    end
    pp tag_id
    @linked_tags = LinkedTag.where(related_tag_id: tag_id)
    @tags = Tag.where(id: @linked_tags.pluck(:tag_id))
    # Show similar tags as well after search. 
    @paginatable_array = Kaminari.paginate_array(@linked_tags).page(params[:page]).per(30)
  end

  def similar
    uri = URI("https://api.stackexchange.com/2.2/questions/#{params['question_id']}/linked?order=desc&sort=activity&site=stackoverflow")
    res = Net::HTTP.get_response(uri)
    @similar_questions = JSON.parse(res.body)
    current_user.follow(LinkedQuestion.find_by(related_post_id: params['question_id']))
  end

  def explore
    uri = URI("https://api.stackexchange.com/2.2/questions/#{params['question_id']}/related?order=desc&sort=activity&site=stackoverflow")
    res = Net::HTTP.get_response(uri)
    @related_questions = JSON.parse(res.body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_pending_questions.html.erb
<% pending_questions.each do |tag, questions| %>
  <table border = 1>
    <% questions.each do |question| %>
      <%= render 'question', :row => question %>
    <% end %>
  </table>
<% end %>

app/views/questions/_question.html.erb
<div id="question<%= question[1] %>">
  <div class="content"><a href="https://stackoverflow.com/questions/<%=question[1]%>" target="_blank"> <%= question[3] %></a></div>
  <div class="user"><%= (question[0].split("|")).join(" ") %></div>
  <div><%= question[2] %></div>
</div>

app/views/questions/_questions.html.erb
<ul class="questions">
  <% questions.each do |question| %>
    <%= render 'question', :row => question %>
  <% end %>
</ul>

app/views/questions/_top.html.erb
<div class="container"> 
	<div class="row">
    <div class="col-2">
      <%= render 'profile/profile' %>
    </div>
    <div class="col-6">
      <%= render @paginatable_array %>
			<%= paginate @paginatable_array %>
    </div>
    <div class="col-2">
    </div>
	</div>
</div>

app/views/questions/answers.html.erb
<% @final_data['items'].each do |post| %>
  <div class="card">
    <h5 class="card-header"><%= post['question'] %></h5>
    <div class="card-body">
      <a href="https://stackoverflow.com/a/<%= post['answer_id'] %>">Your answer: <%= post['score'] %></a>
      <a href="https://stackoverflow.com/a/<%= post['highest_score_id'] %>">Highest score answer: <%= post['highest_score'] %></a>	   
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <% if post['similar_questions']['items'] and post['similar_questions']['items'].count > 0 %>
            <%= post['similar_questions']['items'][0]['title'].html_safe %><%= link_to "Next", questions_similar_path(question_id: post['question_id']), class: "card-link" %>
          <% end %>
        </li>
        <li class="list-group-item">
          <% if  post['related_questions']['items'] and post['related_questions']['items'].count > 0 %>
            <%= post['related_questions']['items'][0]['title'].html_safe %><%= link_to "Next", questions_explore_path(question_id: post['question_id']), class: "card-link" %>
          <% end %>
        </li>
      </ul>
      <%= link_to "Learn", questions_similar_path(question_id: post['question_id']), class: "card-link" %>
      <%= link_to "Explore", questions_explore_path(question_id: post['question_id']), class: "card-link" %>
    </div>
  </div>
<% end %>

app/views/questions/explore.html.erb
<% @related_questions['items'].each do |post| %>
	<div class="card">
	  <h5 class="card-header"><a href="https://stackoverflow.com/questions/<%=post['question_id']%>" target="_blank"><%= post['title'] %></h5>
	  <div class="card-body">
	    <%= link_to "Learn", questions_similar_path(question_id: post['question_id']) %>
	    <%= link_to "Explore", questions_explore_path(question_id: post['question_id']) %>
	  </div>
	</div>
<% end %>

app/views/questions/index.html.erb
<%= render 'top' %>

app/views/questions/search.html.erb
<%= render 'top' %>

app/views/questions/search_by_id.html.erb
<form class="form-inline my-2 my-lg-0">
	<%= form_for :question do |f|%>
	  <%= f.text_field :id, class: "form-control mr-sm-2", placeholder: 'Search' %>
	  <%= f.submit "Search",  class: "btn btn-outline-success my-2 my-sm-0"%>
  <% end %>

app/views/questions/similar.html.erb
<% @similar_questions['items'].each do |post| %>
	<div class="card">
	  <h5 class="card-header"><a href="https://stackoverflow.com/questions/<%=post['question_id']%>" target="_blank"><%= post['title'].html_safe %></h5>
	  <div class="card-body">
	    <%= link_to "Learn", questions_similar_path(question_id: post['question_id']) %>
	    <%= link_to "Explore", questions_explore_path(question_id: post['question_id']) %>
	  </div>
	</div>
<% end %>

app/views/questions/top.js.erb
$('#my-posts').append("<%= escape_javascript(render partial: 'question', collection: @questions) %>")