config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions, only: :index
  get 'questions/search' => 'questions#search'
  get 'questions/top' => 'questions#top'
  get 'questions/signed_in' => 'questions#signed_in'
  get 'questions/answers' => 'questions#answers'
  get 'questions' => 'questions#index'
  resources :tags
  resources :tags do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'questions/similar'
  get 'questions/search_by_id'
  post 'questions/search_id'
  get 'questions/explore'
  post 'tags/follow'
  post 'tags/unfollow'
  get 'profile' => 'profile#show'
end

app/models/linked_tag.rb
class LinkedTag < ApplicationRecord
end

app/views/linked_tags/_linked_tag.html.erb
<div class="card">
  <h5 class="card-header">Tag: 
    <span><%= linked_tag.tag%> 
    <% if current_user.following?(Tag.find(linked_tag.tag_id)) %>
      <%= button_to "Unfollow", tags_unfollow_path(id: linked_tag.tag_id), id: "unfollow_#{linked_tag.tag_id}", remote: true %>
    <% else %>
      <%= button_to "Follow", tags_follow_path(id: linked_tag.tag_id), id: "follow_#{linked_tag.tag_id}", remote: true %>
    <% end %>
    </span>
  </h5>
  <div class="card-body">
    <div class="d-flex p-2"><a href="https://stackoverflow.com/questions/<%=linked_tag.related_tag_id%>" target="_blank">
        <%= LinkedQuestion.find_by(related_post_id: linked_tag.related_tag_id).title.html_safe %></a>
    </div>
    <%= link_to "Learn", questions_similar_path(question_id: linked_tag.related_tag_id) %>
  </div>
</div>