config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions, only: :index
  get 'questions/search' => 'questions#search'
  get 'questions/top' => 'questions#top'
  get 'questions/signed_in' => 'questions#signed_in'
  get 'questions/answers' => 'questions#answers'
  get 'questions' => 'questions#index'
  resources :tags
  resources :tags do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'questions/similar'
  get 'questions/search_by_id'
  post 'questions/search_id'
  get 'questions/explore'
  post 'tags/follow'
  post 'tags/unfollow'
  get 'profile' => 'profile#show'
end

app/models/tag.rb
class Tag < ApplicationRecord
	acts_as_followable
	# def all
 #    Rails.cache.fetch("#{cache_key}/all", expires_in: 12.hours) do
 #      Tag.all
 #    end
 #  end
end

app/controllers/tags_controller.rb
require "uri"
require "net/http"
require 'json'
require 'will_paginate/array'
class TagsController < ApplicationController
	def index
		if params[:name]
		  uri = URI("http://localhost:5000/search_tag?search_tag="+params[:name])
      x = Net::HTTP.get(uri) # => String
      body = JSON.parse(x)
      @user_following_tags = current_user.following_by_type('Tag').where(id: Tag.where(name: body.keys()).pluck(:id)).order(count: :desc)
		  @tags = Tag.where(name: body.keys()).order(count: :desc).where(id: Tag.all.pluck(:id)-@user_following_tags.pluck(:id)).order(count: :desc).page params[:page]
	  else
			@tags = Tag.all.order(count: :desc).page params[:page]
		end
	end

	def follow
		@tag = Tag.find(params[:id])
		User.find_by(auth_token: session[:access_token]).follow(@tag) 
	end

	def unfollow
		@tag = Tag.find(params[:id])
		User.find_by(auth_token: session[:access_token]).stop_following(@tag) 
	end


	def show 
		custom_params = {'word': Tag.find(params["id"]).name}
		x = Net::HTTP.post_form(URI.parse('http://localhost:5000/result'), custom_params)

    body = x.body
    @final_data = JSON.parse(body)
    @name = Tag.find(params["id"]).name
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/follow.js.erb
$("#follow_"+<%= @tag.id %>).hide()
$("#unfollow_"+<%= @tag.id %>).show()

app/views/tags/index.html.erb
<div class="container"> 
  <div class="row">
    <div class="col-2">
      <%= form_tag tags_path, method: :get do %>
        <%= text_field_tag 'name', params[:name], placeholder: "Enter tag" %>
        <%= submit_tag 'Search!' %>
      <% end %>
    </div>
    <div class="col-6">
      <ul class="list-group">
        <% @tags.each do |tag| %>
          <li><%= link_to tag.name, tag, class: "list-group-item" %>
          <%= button_to "Unfollow", tags_unfollow_path(id: tag.id), id: "unfollow_#{tag.id}", remote: true %></li>
          <%= button_to "Follow", tags_follow_path(id: tag.id), id: "follow_#{tag.id}", remote: true, :style => "display: none;" %></li>
      <% end %>
      </ul>
      <%= paginate @tags %>
    </div>
    <div class="col-2">
      <% if @user_following_tags %>
        <% @user_following_tags.each do |tag| %>
          <li><%= link_to tag.name, tag, class: "list-group-item" %>
          <%= button_to "Unfollow", tags_unfollow_path(id: tag.id), id: "unfollow_#{tag.id}", remote: true %></li>
          <%= button_to "Follow", tags_follow_path(id: tag.id), id: "follow_#{tag.id}", remote: true, :style => "display: none;"%>
          </li>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card">
        <h5 class="card-header">Tag: <span><%= @name%></span>, Score: <%=  @final_data['data']['score'] %>, Count: <%= @final_data['data']['count'] %></h5>
        <div class="card-body">
          <div class="d-flex p-2"><a href="https://stackoverflow.com/questions/<%=@final_data['data']['id']%>" target="_blank">
              <%= LinkedQuestion.find_by(related_post_id: @final_data['data']['id']).title %></a></div>
        </div>
      </div>

      <% @final_data['related_tags'].each do |key, value| %>
        <% key.each do |v1, v2| %>
          <div class="card">
            <h5 class="card-header">Tag: <span><%= v1%></span>, Score: <%=  v2['score'] %>, Count: <%= v2['count'] %></h5>
            <div class="card-body">
              <div class="d-flex p-2"><a href="https://stackoverflow.com/questions/<%=v2['id']%>" target="_blank">
                  <%= LinkedQuestion.find_by(related_post_id: v2['id']).title %></a></div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm">
      Top Questions:
        
    </div>
    <div class="col-sm">
      <ul class="list-group">
        <% @final_data['related_tags'].each do |key| %>
         <li class="list-group-item"> <%= key.keys()[0]%> Count: <%= key.values()[0]['count'] %> Score: <%=  key.values()[0]['score'] %></li>
        <% end %>
      </ul> 
    </div>
  </div>
</div>

app/views/tags/unfollow.js.erb
$("#follow_"+<%= @tag.id %>).show()
$("#unfollow_"+<%= @tag.id %>).hide()