config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions, only: :index
  get 'questions/search' => 'questions#search'
  get 'questions/top' => 'questions#top'
  get 'questions/signed_in' => 'questions#signed_in'
  get 'questions/answers' => 'questions#answers'
  get 'questions' => 'questions#index'
  resources :tags
  resources :tags do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'questions/similar'
  get 'questions/search_by_id'
  post 'questions/search_id'
  get 'questions/explore'
  post 'tags/follow'
  post 'tags/unfollow'
  get 'profile' => 'profile#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stackunderflow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">stackunderflow</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <!-- <a class="nav-link" href="#">Questions <span class="sr-only">(current)</span></a> -->
        <%= link_to "Questions", questions_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Answers", questions_answers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Profile", profile_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Options
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Search Questions by ID", questions_search_by_id_path, class:"dropdown-item" %>
          
      </li>
      <li class="nav-item">
        <%= link_to "Tags", tags_path, class:"nav-link" %>
      </li>
    </ul>
    <%= form_tag("/questions/search", method: "get", class:"form-inline my-2 my-lg-0") do %>
      <%= text_field_tag :q, "", class: "form-control mr-sm-2", placeholder: 'Search' %>
      <%= submit_tag "Search",  class: "btn btn-outline-success my-2 my-sm-0"%>
    <% end %>
      <% if not session[:access_token] %>
        <a class="btn btn-outline-success my-2 my-sm-0" type="submit" href="https://stackoverflow.com/oauth?client_id=12430&scope=no_expiry&redirect_uri=http://localhost:3000/questions/signed_in">Stackoverflow Login</a>
      <% else %>
        <span class="navbar-text">
          Name: <%= current_user.name %>
          Reputation: <%= current_user.reputation %>
        </span>
      <% end %>
   </form>
  </div>
</nav>
    <%= yield %>
  </body>
</html>